server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
spring:
  thymeleaf.cache: false
  mvc:
    static-path-pattern: /**
  http.multipart:
    max-request-size: 30MB
    max-file-size: 30MB
  jackson.serialization:
    fail-on-empty-beans: false
logging.level:
  org.springframework: error
  org.apache.shiro: error
  org.hibernate.SQL: error
  org.goodfox.gwola: debug

# Rest API前缀地址
restPath: /api

# App信息
gwola:
  application:
    name: Goodfox Gwola
    shortName: Gwola
    version: 0.1
  # 文件服务文件存储地址
  file:
    path: /Users/sunyu/files
    temp: /Users/sunyu/files/temp
  url: http://localhost:9000
  weixin:
    appId: null
    appSecret: null

#=============================#
#===== Database Settings =====#
#=============================#
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/gwola?useUnicode=true&characterEncoding=utf-8
  username: root
  password: abc123
  driver-class-name: com.mysql.jdbc.Driver
  druid.initialSize: 3
  druid.maxActive: 3
  druid.minIdle: 2
  druid.maxWait: 60000
  druid.timeBetweenEvictionRunsMillis: 60000
  druid.minEvictableIdleTimeMillis: 300000
  druid.validationQuery: SELECT 'x' FROM DUAL

#=============================#
#=====   Email Settings  =====#
#=============================#
mail:
  protocol: smtp
  host: smtp.qq.com
  port: 465
  smtp:
    socketFactory.port: 465
    auth: true
    starttls.enable: true
    debug: true
    starttls.required: true
    socketFactory.fallback: false
  from:
    mail: 3002054@qq.com
    name: 
  username: 3002054@qq.com
  password: 

#=============================#
#=====   Redis Settings  =====#
#=============================#
spring.redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  jedis:
    pool:
      max-active: 8
      max-wait: -1ms
      max-idle: 8
      min-idle: 0
  timeout: 100ms